import React, { useState } from 'react';
import {
  FileText,
  Download,
  Plus,
  ArrowLeft,
  Building,
  Check,
  MapPin,
  Mail,
  Phone,
  MessageSquare,
  Shield,
  Clock,
  UserCheck,
  ChevronLeft,
  ChevronRight,
  Banknote,
  ClipboardCheck,
  FileCheck2,
  Info,
} from 'lucide-react';

interface ContractItem {
  id: string;
  businessName: string;
  businessLogo?: string;
  avatarInitials: string;
  contractType: 'Commission' | 'Salary' | 'Hourly';
  payAmount: string;
  frequency: 'Monthly' | 'Weekly' | 'Bi-weekly';
  commissionRate?: string;
  startDate: string;
  endDate: string;
  status: 'active' | 'pending' | 'expired';
  location: string;
  email: string;
  phone: string;
  reportingTo: string;
  primaryLocation: string;
  slaTerms: string;
  auditLogs: { date: string; status: string; notes: string }[];
}

interface WorkerContractsPageProps {
  workerId: string;
}

export const WorkerContractsPage: React.FC<WorkerContractsPageProps> = () => {
  const seedContracts: ContractItem[] = [
    {
      id: 'CTR-2026-99421',
      businessName: 'Shine Cleaning Services Inc.',
      avatarInitials: 'SC',
      contractType: 'Commission',
      payAmount: '20%',
      frequency: 'Monthly',
      commissionRate: '20%',
      startDate: 'Jun 1, 2026',
      endDate: 'Dec 31, 2026',
      status: 'active',
      location: 'New York, NY',
      email: 'contact@shinecleaning.com',
      phone: '+1 (555) 098-7654',
      reportingTo: 'Sarah Miller (Operations)',
      primaryLocation: 'Manhattan West, Site 4',
      slaTerms:
        'The Service Provider (Worker) agrees to perform professional cleaning duties as specified in the service schedule attached to this agreement. All work must meet the Quality Assurance standards set forth by Shine Cleaning Services Inc.\n\nPayment for services rendered shall be processed on a weekly basis, calculated as the base amount plus the agreed-upon commission percentage of gross billings generated by the Worker during the performance period. Invoices are generated automatically by the URSPOT system every Friday.',
      auditLogs: [
        { date: 'Jun 14, 2026', status: 'Sent', notes: 'Contract invitation sent to worker' },
        { date: 'Jun 12, 2026', status: 'Draft', notes: 'Contract drafted by HR manager' },
      ],
    },
    {
      id: 'CTR-2026-88102',
      businessName: 'FixIt Co.',
      avatarInitials: 'FC',
      contractType: 'Salary',
      payAmount: '$1,500.00',
      frequency: 'Weekly',
      commissionRate: 'N/A',
      startDate: 'Jun 20, 2026',
      endDate: 'Ongoing',
      status: 'pending',
      location: 'Brooklyn, NY',
      email: 'dispatch@fixitco.com',
      phone: '+1 (555) 345-6789',
      reportingTo: 'Dave Henderson (Field Director)',
      primaryLocation: 'Brooklyn Industrial Yard, Bay 3',
      slaTerms:
        'The Service Provider agrees to provide general electrical and plumbing maintenance on on-call rotation. Guaranteed base weekly salary of $1,500.00 disbursed every Friday via direct ACH deposit.\n\nEmergency dispatch after 8:00 PM will accrue supplementary overtime at 1.5x standard equivalent hourly rate.',
      auditLogs: [
        { date: 'Jun 18, 2026', status: 'Sent', notes: 'Offer extended by HR coordinator' },
      ],
    },
    {
      id: 'CTR-2026-77341',
      businessName: 'Logis Group',
      avatarInitials: 'LG',
      contractType: 'Hourly',
      payAmount: '$45.00/hr',
      frequency: 'Bi-weekly',
      commissionRate: 'N/A',
      startDate: 'Jan 1, 2026',
      endDate: 'May 31, 2026',
      status: 'expired',
      location: 'Queens, NY',
      email: 'logistics@logisgroup.com',
      phone: '+1 (555) 890-1234',
      reportingTo: 'Elena Rostova (Fleet Manager)',
      primaryLocation: 'JFK Air Cargo Terminal 4',
      slaTerms:
        'Fixed 5-month seasonal contract for specialized warehouse sorting and cargo transport. Successfully fulfilled with 100% attendance rate.',
      auditLogs: [
        { date: 'May 31, 2026', status: 'Expired', notes: 'Term expired with full sign-off' },
      ],
    },
  ];

  const [contracts, setContracts] = useState<ContractItem[]>(seedContracts);
  const [selectedContract, setSelectedContract] = useState<ContractItem | null>(null);
  const [activeFilter, setActiveFilter] = useState<'all' | 'pending' | 'active' | 'expired'>('active');
  const [actionNotice, setActionNotice] = useState<string | null>(null);

  const filteredContracts = contracts.filter((c) => {
    if (activeFilter === 'all') return true;
    return c.status === activeFilter;
  });

  const handleAcceptContract = (ctr: ContractItem) => {
    const updated = contracts.map((c) =>
      c.id === ctr.id ? { ...c, status: 'active' as const } : c
    );
    setContracts(updated);
    setSelectedContract({ ...ctr, status: 'active' });
    setActionNotice('Contract accepted! Final approval in progress (typical time: 24-48 hrs).');
    setTimeout(() => setActionNotice(null), 4500);
  };

  // =========================================================================
  // VIEW 2: CONTRACT DETAILS VIEW (Exact match to Image 2)
  // =========================================================================
  if (selectedContract) {
    const isPending = selectedContract.status === 'pending';

    return (
      <div className="space-y-6 pb-12">
        {/* Top Header Bar */}
        <div className="flex items-center justify-between pb-3 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={() => setSelectedContract(null)}
              className="flex items-center gap-2 text-xs font-bold text-gray-800 hover:text-black transition-colors cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
              <span className="text-sm font-extrabold text-gray-900">Contract Details</span>
            </button>
            <span className="text-gray-300">|</span>
            <span className="text-xs font-mono font-bold text-gray-500">
              ID: {selectedContract.id}
            </span>
          </div>
        </div>

        {actionNotice && (
          <div className="p-3.5 bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs rounded-xl flex items-center gap-2 animate-in fade-in font-medium">
            <Check className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>{actionNotice}</span>
          </div>
        )}

        {/* Business Header Card */}
        <div className="bg-white rounded-xl p-6 border border-gray-200/90 shadow-2xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded-xl bg-black text-white font-black text-lg flex items-center justify-center shrink-0 shadow-sm">
              {selectedContract.avatarInitials}
            </div>
            <div>
              <h2 className="text-xl font-extrabold text-gray-900 tracking-tight">
                {selectedContract.businessName}
              </h2>
              <div className="flex flex-wrap items-center gap-3 mt-1 text-xs text-gray-500">
                <span className="flex items-center gap-1">
                  <MapPin className="w-3.5 h-3.5 text-gray-400" />
                  {selectedContract.location}
                </span>
                <span>&bull;</span>
                <span className="flex items-center gap-1">
                  <Mail className="w-3.5 h-3.5 text-gray-400" />
                  {selectedContract.email}
                </span>
                <span>&bull;</span>
                <span className="flex items-center gap-1">
                  <Phone className="w-3.5 h-3.5 text-gray-400" />
                  {selectedContract.phone}
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-3 self-start sm:self-auto">
            <button
              type="button"
              className="flex items-center gap-2 px-4 py-2.5 rounded-lg border border-gray-300 bg-white hover:bg-gray-50 text-xs font-bold text-gray-800 transition-colors cursor-pointer"
            >
              <MessageSquare className="w-4 h-4 text-gray-600" />
              <span>Contact Business</span>
            </button>

            {isPending && (
              <button
                type="button"
                onClick={() => handleAcceptContract(selectedContract)}
                className="flex items-center gap-2 px-6 py-2.5 rounded-lg bg-black hover:bg-neutral-800 text-white text-xs font-bold transition-colors cursor-pointer"
              >
                <span>Accept Contract</span>
              </button>
            )}

            {!isPending && (
              <span className="px-4 py-2 rounded-lg bg-emerald-50 text-emerald-700 border border-emerald-200 text-xs font-bold flex items-center gap-1.5">
                <Check className="w-4 h-4" />
                <span>Active Agreement</span>
              </span>
            )}
          </div>
        </div>

        {/* 4-Step Progress Stepper (Exact match to Image 2) */}
        <div className="bg-white rounded-xl p-6 border border-gray-200/90 shadow-2xs">
          <div className="grid grid-cols-4 relative text-center">
            {/* Step 1: SENT */}
            <div className="flex flex-col items-center relative z-10">
              <div className="w-7 h-7 rounded-full bg-black text-white flex items-center justify-center text-xs">
                <Check className="w-3.5 h-3.5" />
              </div>
              <span className="text-xs font-black text-gray-900 tracking-wider uppercase mt-2">
                SENT
              </span>
              <span className="text-[10px] text-gray-400 mt-0.5">Jun 14, 2026</span>
            </div>

            {/* Step 2: PENDING */}
            <div className="flex flex-col items-center relative z-10">
              <div className="w-7 h-7 rounded-full bg-black text-white flex items-center justify-center text-xs font-bold">
                &bull;&bull;&bull;
              </div>
              <span className="text-xs font-black text-gray-900 tracking-wider uppercase mt-2">
                PENDING
              </span>
              <span className="text-[10px] text-gray-400 mt-0.5">Awaiting Review</span>
            </div>

            {/* Step 3: APPROVED */}
            <div className="flex flex-col items-center relative z-10">
              <div className="w-7 h-7 rounded-full border border-gray-300 bg-white text-gray-400 flex items-center justify-center text-xs">
                <Shield className="w-3.5 h-3.5" />
              </div>
              <span className="text-xs font-bold text-gray-400 tracking-wider uppercase mt-2">
                APPROVED
              </span>
              <span className="text-[10px] text-gray-400 mt-0.5">--</span>
            </div>

            {/* Step 4: ACTIVE */}
            <div className="flex flex-col items-center relative z-10">
              <div className="w-7 h-7 rounded-full border border-gray-300 bg-white text-gray-400 flex items-center justify-center text-xs">
                <Check className="w-3.5 h-3.5" />
              </div>
              <span className="text-xs font-bold text-gray-400 tracking-wider uppercase mt-2">
                ACTIVE
              </span>
              <span className="text-[10px] text-gray-400 mt-0.5">--</span>
            </div>

            {/* Connecting line */}
            <div className="absolute top-3.5 left-[12%] right-[12%] h-0.5 bg-gray-200 -z-0" />
          </div>
        </div>

        {/* 2-Column Terms & Decision Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Column (approx 7 cols): Terms Card */}
          <div className="lg:col-span-8 bg-white rounded-xl p-6 border border-gray-200/90 shadow-2xs space-y-6">
            <div className="flex items-center justify-between pb-4 border-b border-gray-100">
              <div className="flex items-center gap-2.5">
                <FileText className="w-4 h-4 text-gray-700" />
                <h3 className="font-extrabold text-sm text-gray-900">Contract Terms</h3>
              </div>

              <button
                type="button"
                className="flex items-center gap-1.5 text-xs font-bold text-gray-800 hover:text-black cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download PDF</span>
              </button>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-6 text-xs">
              <div>
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                  CONTRACT TYPE
                </span>
                <span className="text-sm font-extrabold text-gray-900 mt-1 block">
                  {selectedContract.contractType}
                </span>
              </div>

              <div>
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                  PAY AMOUNT
                </span>
                <span className="text-sm font-extrabold text-gray-900 mt-1 block">
                  $1,500.00
                </span>
              </div>

              <div>
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                  FREQUENCY
                </span>
                <span className="text-sm font-extrabold text-gray-900 mt-1 block">
                  {selectedContract.frequency}
                </span>
              </div>

              <div>
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                  COMMISSION %
                </span>
                <span className="text-sm font-extrabold text-gray-900 mt-1 block">
                  {selectedContract.commissionRate || '20%'}
                </span>
              </div>

              <div>
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                  START DATE
                </span>
                <span className="text-sm font-extrabold text-gray-900 mt-1 block">
                  {selectedContract.startDate}
                </span>
              </div>

              <div>
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                  END DATE
                </span>
                <span className="text-sm font-extrabold text-gray-900 mt-1 block">
                  {selectedContract.endDate}
                </span>
              </div>
            </div>

            {/* SLA Box */}
            <div className="bg-gray-50 border border-gray-200/80 rounded-xl p-5">
              <span className="text-[10px] font-extrabold text-gray-500 uppercase tracking-wider block mb-2">
                SERVICE LEVEL AGREEMENT & TERMS
              </span>
              <p className="text-xs text-gray-700 leading-relaxed whitespace-pre-line font-medium">
                {selectedContract.slaTerms}
              </p>
            </div>
          </div>

          {/* Right Column (approx 4 cols): Decision Card & Job Site Info */}
          <div className="lg:col-span-4 space-y-6">
            {/* Awaiting Your Decision Card */}
            <div className="bg-black text-white rounded-xl p-6 shadow-md relative overflow-hidden">
              <h4 className="font-extrabold text-base text-white tracking-tight mb-2">
                Awaiting Your Decision
              </h4>
              <p className="text-xs text-neutral-300 leading-relaxed mb-4">
                Review the terms carefully. Once accepted, this contract will move to the "Pending
                Approval" phase for final verification before becoming active.
              </p>

              <div className="flex items-center gap-2 text-xs text-neutral-400 pt-3 border-t border-neutral-800">
                <Info className="w-4 h-4 text-neutral-400 shrink-0" />
                <span>Average approval time: 24-48 hours.</span>
              </div>
            </div>

            {/* Job Site Info */}
            <div className="bg-white rounded-xl p-5 border border-gray-200/90 shadow-2xs space-y-4">
              <span className="text-[10px] font-extrabold text-gray-400 uppercase tracking-wider block">
                JOB SITE INFORMATION
              </span>

              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-lg bg-gray-100 flex items-center justify-center shrink-0">
                  <MapPin className="w-4 h-4 text-gray-700" />
                </div>
                <div>
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                    PRIMARY LOCATION
                  </span>
                  <span className="text-xs font-extrabold text-gray-900 mt-0.5 block">
                    {selectedContract.primaryLocation}
                  </span>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-lg bg-gray-100 flex items-center justify-center shrink-0">
                  <UserCheck className="w-4 h-4 text-gray-700" />
                </div>
                <div>
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                    REPORTING TO
                  </span>
                  <span className="text-xs font-extrabold text-gray-900 mt-0.5 block">
                    {selectedContract.reportingTo}
                  </span>
                </div>
              </div>
            </div>

            {/* Cryptographic Seal */}
            <div className="p-3.5 bg-gray-50 border border-gray-200 rounded-xl flex items-center gap-3 text-[11px] text-gray-500 font-medium">
              <Shield className="w-4 h-4 text-gray-600 shrink-0" />
              <span>This document is cryptographically signed and secured by URSPOT Enterprise Shield.</span>
            </div>
          </div>
        </div>

        {/* Status Change Log Table */}
        <div className="bg-white rounded-xl border border-gray-200/90 shadow-2xs overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-100">
            <h3 className="font-extrabold text-sm text-gray-900">Status Change Log</h3>
          </div>

          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-gray-50 text-[10px] font-bold uppercase tracking-wider text-gray-400 border-b border-gray-100">
                <th className="py-3 px-6">DATE</th>
                <th className="py-3 px-6">STATUS</th>
                <th className="py-3 px-6">NOTES</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 font-medium text-gray-700">
              {selectedContract.auditLogs.map((log, idx) => (
                <tr key={idx} className="hover:bg-gray-50/50">
                  <td className="py-3.5 px-6 font-bold text-gray-900">{log.date}</td>
                  <td className="py-3.5 px-6">
                    <span className="px-2.5 py-0.5 rounded-full bg-gray-100 text-gray-600 text-[10px] font-bold">
                      {log.status}
                    </span>
                  </td>
                  <td className="py-3.5 px-6 text-gray-600">{log.notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  // =========================================================================
  // VIEW 1: CONTRACTS LIST VIEW (Exact match to Image 1)
  // =========================================================================
  return (
    <div className="space-y-6 pb-12">
      {/* Header with Title & Action Buttons */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight">My Contracts</h1>
          <p className="text-xs text-gray-500 font-medium mt-1">
            Review and manage your professional service agreements.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            type="button"
            className="flex items-center gap-2 px-4 py-2 rounded-lg border border-gray-300 bg-white hover:bg-gray-50 text-xs font-bold text-gray-800 shadow-2xs transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export PDF</span>
          </button>

          <button
            type="button"
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-black hover:bg-neutral-800 text-white text-xs font-bold shadow-2xs transition-colors cursor-pointer"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>New Contract Request</span>
          </button>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-6 border-b border-gray-200 text-xs font-semibold">
        {(['pending', 'active', 'expired', 'all'] as const).map((tab) => (
          <button
            key={tab}
            type="button"
            onClick={() => setActiveFilter(tab)}
            className={`pb-3 capitalize transition-colors cursor-pointer ${
              activeFilter === tab
                ? 'text-black border-b-2 border-black font-bold'
                : 'text-gray-400 hover:text-black'
            }`}
          >
            {tab}
          </button>
        ))}
      </div>

      {/* Contracts Table */}
      <div className="bg-white rounded-xl border border-gray-200/90 shadow-2xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-50/50 border-b border-gray-100 text-[11px] font-bold uppercase tracking-wider text-gray-400">
                <th className="py-3.5 px-6">BUSINESS</th>
                <th className="py-3.5 px-6">CONTRACT TYPE</th>
                <th className="py-3.5 px-6">PAY AMOUNT</th>
                <th className="py-3.5 px-6">FREQUENCY</th>
                <th className="py-3.5 px-6">START DATE</th>
                <th className="py-3.5 px-6">END DATE</th>
                <th className="py-3.5 px-6">STATUS</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 text-xs text-gray-700 font-medium">
              {filteredContracts.map((c) => (
                <tr
                  key={c.id}
                  onClick={() => setSelectedContract(c)}
                  className="hover:bg-gray-50/70 transition-colors cursor-pointer"
                >
                  <td className="py-4 px-6">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-gray-100 font-bold text-gray-800 flex items-center justify-center text-xs shrink-0">
                        {c.avatarInitials}
                      </div>
                      <span className="font-extrabold text-gray-900">{c.businessName}</span>
                    </div>
                  </td>
                  <td className="py-4 px-6 text-gray-600 font-medium">{c.contractType}</td>
                  <td className="py-4 px-6 font-black text-gray-900">{c.payAmount}</td>
                  <td className="py-4 px-6 text-gray-600 font-medium">{c.frequency}</td>
                  <td className="py-4 px-6 text-gray-900 font-semibold">{c.startDate}</td>
                  <td className="py-4 px-6 text-gray-500 font-medium">
                    {c.endDate === 'Ongoing' ? (
                      <span className="italic text-gray-400">Ongoing</span>
                    ) : (
                      c.endDate
                    )}
                  </td>
                  <td className="py-4 px-6">
                    <span
                      className={`px-3 py-1 rounded-full text-xs font-bold inline-block uppercase ${
                        c.status === 'active'
                          ? 'bg-emerald-50 text-emerald-600 border border-emerald-100'
                          : c.status === 'pending'
                          ? 'bg-amber-50 text-amber-600 border border-amber-100'
                          : 'bg-gray-100 text-gray-500'
                      }`}
                    >
                      {c.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div className="px-6 py-4 flex items-center justify-between border-t border-gray-100 text-xs text-gray-500">
          <span>Showing 1-3 of 12 contracts</span>
          <div className="flex items-center gap-1.5 font-bold">
            <button
              type="button"
              className="w-7 h-7 flex items-center justify-center rounded border border-gray-200 hover:bg-gray-50 cursor-pointer"
            >
              <ChevronLeft className="w-3.5 h-3.5" />
            </button>
            <button
              type="button"
              className="w-7 h-7 flex items-center justify-center rounded bg-black text-white cursor-pointer"
            >
              1
            </button>
            <button
              type="button"
              className="w-7 h-7 flex items-center justify-center rounded border border-gray-200 hover:bg-gray-50 text-gray-700 cursor-pointer"
            >
              2
            </button>
            <button
              type="button"
              className="w-7 h-7 flex items-center justify-center rounded border border-gray-200 hover:bg-gray-50 text-gray-700 cursor-pointer"
            >
              3
            </button>
            <span className="px-1 text-gray-400">...</span>
            <button
              type="button"
              className="w-7 h-7 flex items-center justify-center rounded border border-gray-200 hover:bg-gray-50 cursor-pointer"
            >
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>

      {/* Bottom 3 Summary Cards (Exact match to Image 1) */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
        {/* Card 1: Total Revenue (Black Card) */}
        <div className="bg-black text-white rounded-xl p-6 shadow-md flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-black uppercase tracking-wider text-neutral-400">
              TOTAL REVENUE (YTD)
            </span>
            <Banknote className="w-4 h-4 text-neutral-400" />
          </div>
          <div className="mt-4">
            <span className="text-3xl font-black text-white tracking-tight block">
              $42,850.00
            </span>
            <span className="text-[11px] font-semibold text-neutral-400 mt-1 block">
              +12% from previous year
            </span>
          </div>
        </div>

        {/* Card 2: Active Contracts */}
        <div className="bg-white rounded-xl p-6 border border-gray-200/90 shadow-2xs flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0">
            <ClipboardCheck className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-gray-400 block">
              ACTIVE CONTRACTS
            </span>
            <span className="text-3xl font-black text-gray-900 tracking-tight block mt-0.5">
              08
            </span>
          </div>
        </div>

        {/* Card 3: Pending Approval */}
        <div className="bg-white rounded-xl p-6 border border-gray-200/90 shadow-2xs flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center shrink-0">
            <FileCheck2 className="w-6 h-6" />
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-gray-400 block">
              PENDING APPROVAL
            </span>
            <span className="text-3xl font-black text-gray-900 tracking-tight block mt-0.5">
              03
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
